import { useCallback, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { ArrowLeft, ArrowUp, ArrowDown, Plus, Eye, EyeOff, Save, Trash2, RotateCcw, History, Globe, Loader2, Palette, Layers, Copy, Monitor, Smartphone, Tablet, X, Check, Upload, Download, Settings2, Type, PanelLeftClose, ExternalLink } from "lucide-react";
import { useAuth } from "@/contexts/auth";
import { Button } from "@/components/ui/button";
import { SchemaForm } from "@/components/landing-editor/schema-form";
import { getBlockSchema, BLOCK_SCHEMAS, SECTION_FIELDS, BRAND_FIELDS, type FieldSchema } from "@/components/landing-editor/block-schemas";
import { landingEditorApi, type AdminLandingBlock, type AdminLandingTheme, type AdminLandingSnapshot } from "@/lib/landing-editor-api";
import { STUDIO_PRESETS } from "@/components/landing-studio/presets";
import type { LandingApiResponse } from "@/components/landing-blocks/types";
import "@/components/landing-studio/editor.css";
const object = (v:unknown):Record<string,unknown> => v && typeof v === "object" && !Array.isArray(v) ? v as Record<string,unknown> : {};
const clean = (v:unknown) => { const {__landingEditor: _metadata,...rest}=object(v); return rest; };
const label = (b:AdminLandingBlock) => b.type === "custom" ? BLOCK_SCHEMAS.custom.variants.find(v=>v.value===b.variant)?.label ?? "Секция" : BLOCK_SCHEMAS[b.type]?.label ?? b.type;
const THEME_FIELDS: FieldSchema[] = [
 {key:"primaryColor",label:"Главный акцент и кнопки",type:"color"},{key:"accentColor",label:"Дополнительный акцент",type:"color"},{key:"backgroundColor",label:"Фон страницы",type:"color"},{key:"textColor",label:"Основной текст",type:"color"},
 {key:"fontFamily",label:"Шрифт",type:"select",options:["Onest","Manrope","Inter","Geist","IBM Plex Sans"].map(value=>({value,label:value}))},
 {key:"borderRadius",label:"Скругления",type:"select",options:[{value:"0px",label:"Прямые углы"},{value:"6px",label:"Небольшие · 6 px"},{value:"12px",label:"Мягкие · 12 px"},{value:"16px",label:"Округлые · 16 px"}]},
 {key:"containerWidth",label:"Ширина страницы",type:"select",options:[{value:"1200px",label:"Компактная · 1200 px"},{value:"1360px",label:"Средняя · 1360 px"},{value:"1440px",label:"Широкая · 1440 px"},{value:"1680px",label:"Очень широкая · 1680 px"}]},
 {key:"customCss",label:"Дополнительный CSS",type:"textarea",rows:6,hint:"Для разработчиков. Применяется только на лендинге; используйте .sn-landing в селекторах."},
];
export function LandingEditorPage() {
 const {state}=useAuth();const token=state.accessToken;
 const [blocks,setBlocks]=useState<AdminLandingBlock[]>([]),[theme,setTheme]=useState<Record<string,unknown>>({}),[baseTheme,setBaseTheme]=useState<AdminLandingTheme|null>(null);
 const [selected,setSelected]=useState(""),[tab,setTab]=useState<"content"|"style">("content"),[panel,setPanel]=useState<"blocks"|"theme"|"brand">("blocks");
 const [dirty,setDirty]=useState<Set<string>>(new Set()),[themeDirty,setThemeDirty]=useState(false),[pending,setPending]=useState(false),[enabled,setEnabled]=useState(true);
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const [width,setWidth]=useState(1440),[language,setLanguage]=useState("ru"),[addOpen,setAddOpen]=useState(false),[historyOpen,setHistoryOpen]=useState(false),[snapshots,setSnapshots]=useState<AdminLandingSnapshot[]>([]);
 const [inspector,setInspector]=useState(true),[previewKey,setPreviewKey]=useState(0),[zoom,setZoom]=useState(1);
 const frame=useRef<HTMLIFrameElement>(null),canvas=useRef<HTMLDivElement>(null),file=useRef<HTMLInputElement>(null);
 const busyRef=useRef(false);
 const reload=useCallback(async()=>{if(!token)return;const [b,t,status,e]=await Promise.all([landingEditorApi.listBlocks(token),landingEditorApi.getTheme(token),landingEditorApi.draftsStatus(token),landingEditorApi.getStatus(token)]);
   setBlocks(b);setBaseTheme(t);setTheme({...t,...object(t.draft)});setPending(status.hasBlockDrafts||status.hasThemeDraft);setEnabled(e.enabled);setDirty(new Set());setThemeDirty(false);setSelected(s=>b.some(x=>x.id===s)?s:b[0]?.id??"");
 },[token]);
 useEffect(()=>{reload().catch(e=>setError(String(e))).finally(()=>setLoading(false));},[reload]);
 const hasLocal=dirty.size>0||themeDirty;
 useEffect(()=>{const protect=(e:BeforeUnloadEvent)=>{if(hasLocal){e.preventDefault();e.returnValue="";}};window.addEventListener("beforeunload",protect);return()=>window.removeEventListener("beforeunload",protect);},[hasLocal]);
 const block=blocks.find(b=>b.id===selected);const hero=blocks.find(b=>b.type==="hero");
 const schema=block?getBlockSchema(block.type,block.variant):null;
 const localized=(b:AdminLandingBlock)=>{const all=object(b.i18nDraft??b.i18n);return object(all[language]??all.ru??all.en);};
 const preview=useMemo<LandingApiResponse>(()=>({lang:language,theme:{...theme,fontPresets:(baseTheme?.fontPresets??[])},blocks:blocks.filter(b=>b.visible).map(b=>({id:b.id,type:b.type,variant:b.variant,order:b.order,props:clean(b.propsDraft??b.props),text:localized(b)}))}),[blocks,theme,baseTheme,language]);
 const sendPreview=useCallback(()=>frame.current?.contentWindow?.postMessage({type:"stealthnet-landing:preview",data:preview},location.origin),[preview]);
 useEffect(()=>{const timer=setTimeout(sendPreview,100);return()=>clearTimeout(timer);},[sendPreview]);
 useEffect(()=>{const receive=(e:MessageEvent)=>{if(e.origin!==location.origin||e.source!==frame.current?.contentWindow)return;if(e.data?.type==="stealthnet-landing:ready")sendPreview();if(e.data?.type==="stealthnet-landing:edit-block"&&typeof e.data.id==="string"){setSelected(e.data.id);setPanel("blocks");setInspector(true);}};window.addEventListener("message",receive);return()=>window.removeEventListener("message",receive);},[sendPreview]);
 useEffect(()=>{const node=canvas.current;if(!node)return;const observer=new ResizeObserver(()=>setZoom(Math.min(1,(node.clientWidth-32)/width)));observer.observe(node);return()=>observer.disconnect();},[width,loading,inspector]);
 const changeBlock=(id:string,update:Partial<AdminLandingBlock>)=>{setBlocks(bs=>bs.map(b=>b.id===id?{...b,...update}:b));setDirty(d=>new Set([...d,id]));};
 const changeProps=(b:AdminLandingBlock,value:Record<string,unknown>)=>changeBlock(b.id,{propsDraft:value});
 const changeText=(b:AdminLandingBlock,value:Record<string,unknown>)=>changeBlock(b.id,{i18nDraft:{...object(b.i18nDraft??b.i18n),[language]:value}});
 const saveLocal=async()=>{if(!token)return;for(const b of blocks.filter(b=>dirty.has(b.id)))await landingEditorApi.updateBlock(token,b.id,{propsDraft:clean(b.propsDraft??b.props),i18nDraft:b.i18nDraft??b.i18n,visible:b.visible,variant:b.variant,order:b.order});if(themeDirty){const {id:_id,draft:_draft,updatedAt:_updated,...settings}=theme;await landingEditorApi.updateThemeDraft(token,settings);}};
 const run=async(action:()=>Promise<void>)=>{if(busyRef.current)return;busyRef.current=true;setBusy(true);setError("");setMessage("");try{await action();}catch(e){setError(String(e));}finally{busyRef.current=false;setBusy(false);}};
 const save=()=>run(async()=>{await saveLocal();await reload();setMessage("Черновик сохранён. Сайт изменится после публикации.");});
 const publish=()=>run(async()=>{if(!token)return;await saveLocal();await landingEditorApi.publishAll(token);await reload();setMessage("Лендинг опубликован");});
 const discard=()=>{if(!confirm("Отменить все неопубликованные изменения страницы?"))return;void run(async()=>{if(!token)return;await landingEditorApi.discardAllDrafts(token);await reload();setPreviewKey(k=>k+1);setMessage("Вернулись к опубликованной версии");});};
 const move=(id:string,by:number)=>{const from=blocks.findIndex(b=>b.id===id),to=from+by;if(to<0||to>=blocks.length)return;const next=[...blocks];[next[from],next[to]]=[next[to],next[from]];setBlocks(next.map((b,i)=>({...b,order:(i+1)*10})));setDirty(new Set([...dirty,...next.map(b=>b.id)]));};
 const create=(type:string,variant:string,copy?:AdminLandingBlock)=>run(async()=>{if(!token)return;await saveLocal();const b=await landingEditorApi.createBlock(token,{type,variant,...(copy?{props:clean(copy.propsDraft??copy.props),i18n:copy.i18nDraft??copy.i18n}:{})});await reload();setSelected(b.id);setPanel("blocks");setInspector(true);setAddOpen(false);setMessage(copy?"Копия добавлена в черновик":"Секция добавлена в черновик");});
 const remove=(b:AdminLandingBlock)=>{if(!confirm(`Убрать секцию «${label(b)}»? На сайте она исчезнет после публикации.`))return;void run(async()=>{if(!token)return;await saveLocal();await landingEditorApi.deleteBlock(token,b.id);await reload();setMessage("Секция убрана из черновика");});};
 const history=()=>run(async()=>{if(!token)return;setSnapshots(await landingEditorApi.listSnapshots(token));setHistoryOpen(true);});
 const snapshot=()=>run(async()=>{if(!token)return;await saveLocal();await landingEditorApi.createSnapshot(token,`Ручная копия · ${new Date().toLocaleString("ru-RU")}`);await reload();setMessage("Копия страницы сохранена в истории");});
 const applyPreset=(preset:typeof STUDIO_PRESETS[number])=>{setTheme(t=>({...t,...preset.theme}));setThemeDirty(true);if(hero)changeProps(hero,{...clean(hero.propsDraft??hero.props),...preset.scene});setMessage(`Оформление ${preset.name} применено к черновику. Тексты сохранены.`);};
 const exportPage=()=>{const payload={format:"stealthnet-landing",version:1,theme,blocks:blocks.map(b=>({type:b.type,variant:b.variant,visible:b.visible,props:clean(b.propsDraft??b.props),i18n:b.i18nDraft??b.i18n}))};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download="landing-template.json";a.click();URL.revokeObjectURL(url);};
 const importPage=async(f:File)=>{try{if(f.size>2*1024*1024)throw new Error("Шаблон должен быть меньше 2 МБ");const data=JSON.parse(await f.text());if(data.format!=="stealthnet-landing"||data.version!==1||!Array.isArray(data.blocks)||data.blocks.length>100||data.blocks.some((b:AdminLandingBlock)=>!BLOCK_SCHEMAS[b.type]||!getBlockSchema(b.type,b.variant)))throw new Error("Неподдерживаемый файл шаблона");if(!confirm("Заменить черновик страницы импортированным шаблоном? Текущая версия будет сохранена в истории."))return;await run(async()=>{if(!token)return;await saveLocal();await landingEditorApi.createSnapshot(token,"Перед импортом шаблона");for(const b of blocks)await landingEditorApi.deleteBlock(token,b.id);for(const b of data.blocks)await landingEditorApi.createBlock(token,{type:b.type,variant:b.variant,props:clean(b.props),i18n:object(b.i18n),visible:b.visible!==false});const keys=THEME_FIELDS.map(f=>f.key);await landingEditorApi.updateThemeDraft(token,Object.fromEntries(Object.entries(object(data.theme)).filter(([k])=>keys.includes(k))));await reload();setMessage("Шаблон импортирован в черновик. Проверьте изображения и ссылки перед публикацией.");});}catch(e){setError(String(e));}finally{if(file.current)file.current.value="";}};
 if(loading)return <div className="p-12 flex justify-center gap-3" role="status"><Loader2 className="animate-spin"/>Загружаем конструктор…</div>;
 return <div className="sn-editor">
  <header className="sn-editor-toolbar"><div className="sn-editor-title"><a href="/admin/settings" aria-label="Вернуться в настройки"><ArrowLeft size={20}/></a><div><h1>Конструктор лендинга</h1><span>{hasLocal?"Есть несохранённые изменения":pending?"Черновик · готов к публикации":"Все изменения опубликованы"}</span></div></div><div className="sn-editor-tools"><button disabled={busy} onClick={()=>void run(async()=>{if(!token)return;const e=await landingEditorApi.setStatus(token,!enabled);setEnabled(e.enabled);})} className={enabled?"sn-enabled":""} title="Включение и выключение сайта применяется сразу"><span/>{enabled?"Сайт включён":"Сайт выключен"}</button><button title="История версий" disabled={busy} onClick={history}><History size={17}/><span>История</span></button><button title="Сохранить черновик" disabled={busy||!hasLocal} onClick={save}><Save size={17}/><span>Сохранить</span></button><button className="sn-editor-publish" disabled={busy||(!pending&&!hasLocal)} onClick={publish}>{busy?<Loader2 size={17} className="animate-spin"/>:<Check size={17}/>}Опубликовать</button></div></header>
  {(error||message)&&<div className={error?"sn-editor-notice sn-editor-error":"sn-editor-notice"} role={error?"alert":"status"}>{error||message}<button aria-label="Закрыть сообщение" onClick={()=>{setMessage("");setError("");}}><X size={15}/></button></div>}
  <fieldset disabled={busy} className="sn-editor-workspace">
   <aside className="sn-editor-sidebar"><div className="sn-editor-modes"><button className={panel==="blocks"?"active":""} onClick={()=>{setPanel("blocks");setInspector(true);}}><Layers size={17}/>Секции</button><button className={panel==="theme"?"active":""} onClick={()=>{setPanel("theme");setInspector(true);}}><Palette size={17}/>Стиль</button><button className={panel==="brand"?"active":""} onClick={()=>{setPanel("brand");setInspector(true);}}><Globe size={17}/>Бренд</button></div>
   <div className="sn-sidebar-heading"><strong>Структура страницы</strong><span>{blocks.length}</span></div>
   <div className="sn-block-list">{blocks.map((b,i)=><div key={b.id} className={`sn-block-row ${selected===b.id&&panel==="blocks"?"active":""} ${!b.visible?"is-hidden":""}`}><button className="sn-block-name" onClick={()=>{setSelected(b.id);setPanel("blocks");setInspector(true);}}><span className="sn-block-icon">{b.type==="hero"?<Globe size={17}/>:b.type==="tariffs"?<Layers size={17}/>:<Type size={17}/>}</span><span>{label(b)}</span>{(dirty.has(b.id)||b.propsDraft||b.i18nDraft)&&<i title="Изменено в черновике"/>}</button><button aria-label={b.visible?`Скрыть ${label(b)}`:`Показать ${label(b)}`} onClick={()=>changeBlock(b.id,{visible:!b.visible})}>{b.visible?<Eye size={14}/>:<EyeOff size={14}/>}</button><div className="sn-block-order"><button aria-label={`Поднять ${label(b)}`} disabled={i===0} onClick={()=>move(b.id,-1)}><ArrowUp size={12}/></button><button aria-label={`Опустить ${label(b)}`} disabled={i===blocks.length-1} onClick={()=>move(b.id,1)}><ArrowDown size={12}/></button></div></div>)}</div>
   <button className="sn-add-section" onClick={()=>setAddOpen(true)} disabled={busy}><Plus size={17}/>Добавить секцию</button>
   <div className="sn-sidebar-bottom"><p>Настраивайте страницу в черновике. Посетители увидят её после публикации.</p><div><button onClick={snapshot} disabled={busy}><Copy size={14}/>Создать копию</button><button onClick={discard} disabled={busy||(!hasLocal&&!pending)}><RotateCcw size={14}/>Отменить</button></div><div><button onClick={exportPage}><Download size={14}/>Экспорт</button><button onClick={()=>file.current?.click()} disabled={busy}><Upload size={14}/>Импорт</button></div><input ref={file} type="file" accept="application/json,.json" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void importPage(f);}}/></div></aside>
   <div className="sn-editor-canvas-column"><div className="sn-preview-toolbar"><div className="sn-device-switch">{[{w:1440,icon:Monitor,label:"Компьютер"},{w:768,icon:Tablet,label:"Планшет"},{w:390,icon:Smartphone,label:"Телефон"}].map(({w,icon:Icon,label})=><button key={w} aria-label={label} title={label} aria-pressed={width===w} className={width===w?"active":""} onClick={()=>setWidth(w)}><Icon size={17}/></button>)}</div><span>{width} px · {Math.round(zoom*100)}%</span><div className="sn-preview-right"><a href="/" target="_blank" rel="noreferrer" title="Открыть опубликованный сайт"><ExternalLink size={16}/></a><button onClick={()=>setInspector(!inspector)} aria-label={inspector?"Скрыть настройки":"Показать настройки"}><PanelLeftClose size={17}/></button></div></div><div className="sn-editor-canvas" ref={canvas}><div className="sn-preview-scaled" style={{width:width*zoom,height:Math.max(700,900*zoom)}}><iframe key={previewKey} ref={frame} src="/admin/landing-preview" title="Предпросмотр лендинга" onLoad={sendPreview} style={{width,height:Math.max(900,760/Math.max(zoom,.2)),transform:`scale(${zoom})`}}/></div></div><div className="sn-preview-caption"><Eye size={13}/>Предпросмотр · нажмите «Редактировать секцию» на странице</div></div>
   {inspector&&<aside className="sn-editor-inspector"><div className="sn-inspector-heading"><div><span>{panel==="theme"?"Оформление страницы":panel==="brand"?"Ваш бренд":"Настройки секции"}</span><h2>{panel==="theme"?"Стиль и цвета":panel==="brand"?"Бренд и навигация":block?label(block):"Выберите секцию"}</h2></div><button onClick={()=>setInspector(false)} aria-label="Закрыть настройки"><X size={17}/></button></div>
   <div className="sn-inspector-body">{panel==="theme"?<><div className="sn-presets">{STUDIO_PRESETS.map(p=><button key={p.id} onClick={()=>applyPreset(p)}><span style={{background:p.theme.backgroundColor,color:p.theme.textColor}}><span style={{background:p.theme.primaryColor}}/><b>Aa</b></span><strong>{p.name}</strong><small>{p.description}</small></button>)}</div><SchemaForm fields={THEME_FIELDS} value={theme} onChange={v=>{setTheme(v);setThemeDirty(true);}}/></>:panel==="brand"?hero?<SchemaForm fields={BRAND_FIELDS} value={{showHeader:true,stickyHeader:true,...clean(hero.propsDraft??hero.props)}} onChange={v=>changeProps(hero,v)}/>:<p>Добавьте главный экран, чтобы настроить бренд и навигацию.</p>:block&&schema?<>
     <div className="sn-inspector-tabs"><button className={tab==="content"?"active":""} onClick={()=>setTab("content")}><Type size={15}/>Содержимое</button><button className={tab==="style"?"active":""} onClick={()=>setTab("style")}><Settings2 size={15}/>Оформление</button></div>
     {tab==="content"?<><div className="sn-language"><label htmlFor="landing-language">Язык текстов</label><select id="landing-language" value={language} onChange={e=>setLanguage(e.target.value)}><option value="ru">Русский</option><option value="en">English</option></select></div><SchemaForm fields={schema.i18nFields} value={localized(block)} onChange={v=>changeText(block,v)}/>{schema.propsFields.filter(f=>["items","steps","links","offerLink","privacyLink"].includes(f.key)).length>0&&<div className="sn-inspector-group"><SchemaForm fields={schema.propsFields.filter(f=>["items","steps","links","offerLink","privacyLink"].includes(f.key))} value={clean(block.propsDraft??block.props)} onChange={v=>changeProps(block,v)}/></div>}</>:<><SchemaForm fields={schema.propsFields.filter(f=>!["items","steps","links","offerLink","privacyLink"].includes(f.key))} value={block.type==="hero"?{sceneType:"spatial",sceneColor:"#a0a3ff",sceneMaterial:"glass",sceneMotion:true,sceneSpeed:1,showSecondary:true,showRightCard:true,...clean(block.propsDraft??block.props)}:clean(block.propsDraft??block.props)} onChange={v=>changeProps(block,v)}/><details className="sn-section-options" open><summary>Фон, размеры и видимость</summary><SchemaForm fields={SECTION_FIELDS} value={clean(block.propsDraft??block.props)} onChange={v=>changeProps(block,v)}/></details></>}
     <div className="sn-block-actions"><Button variant="outline" size="sm" disabled={busy} onClick={()=>create(block.type,block.variant,block)}><Copy size={14}/>Дублировать</Button><Button variant="outline" size="sm" disabled={busy} onClick={()=>remove(block)}><Trash2 size={14}/>Удалить</Button></div>
   </>:<p>Выберите секцию слева или добавьте новую.</p>}</div></aside>}
  </fieldset>
  {addOpen&&<StudioDialog onClose={()=>setAddOpen(false)} labelledBy="add-section-title"><div className="sn-dialog-heading"><h2 id="add-section-title">Добавить секцию</h2><button aria-label="Закрыть" onClick={()=>setAddOpen(false)}><X/></button></div><div className="sn-section-library">{Object.values(BLOCK_SCHEMAS).flatMap(s=>s.variants.map(v=><button key={`${s.type}/${v.value}`} disabled={busy} onClick={()=>create(s.type,v.value)}><span className={`sn-section-mini sn-section-mini-${s.type}`}><i/><i/><i/></span><strong>{s.type==="custom"?v.label:s.label}</strong><p>{s.type==="custom"?v.label:v.label+" · "+s.description}</p><span>Добавить <Plus size={14}/></span></button>))}</div></StudioDialog>}
  {historyOpen&&<StudioDialog onClose={()=>setHistoryOpen(false)} labelledBy="history-title"><div className="sn-dialog-heading"><h2 id="history-title">История страницы</h2><button aria-label="Закрыть" onClick={()=>setHistoryOpen(false)}><X/></button></div><p className="sn-history-hint">Перед публикацией автоматически создаётся копия. Восстановление сразу меняет опубликованный сайт.</p>{snapshots.length===0?<p>Сохранённых версий пока нет.</p>:snapshots.map(s=><div key={s.id} className="sn-history-row"><div><strong>{s.label?.replace("auto-before-publish","Перед публикацией").replace("auto-before-restore","Перед восстановлением")||"Сохранённая версия"}</strong><small>{new Date(s.createdAt).toLocaleString("ru-RU")}</small></div><button disabled={busy} onClick={()=>{if(!confirm("Восстановить эту версию на сайте? Текущая версия будет сохранена в истории."))return;void run(async()=>{if(!token)return;await landingEditorApi.restoreSnapshot(token,s.id);await reload();setHistoryOpen(false);setMessage("Версия восстановлена");});}}>Восстановить</button></div>)}</StudioDialog>}
 </div>;
}

function StudioDialog({children,onClose,labelledBy}:{children:ReactNode;onClose:()=>void;labelledBy:string}) {
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const dialog=ref.current;dialog?.showModal();return()=>dialog?.close();},[]);
 return <dialog ref={ref} className="sn-studio-dialog" aria-labelledby={labelledBy} onCancel={onClose} onClose={onClose} onClick={e=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)onClose();}}}>{children}</dialog>;
}
